---
title: "Social engagement pre- and during Covid-19 pandemic-ATUS"
author: "Jiao YU"
date: "2/4/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message= F}
library(foreign)
library(psych)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(lubridate)
library(survey)
library(egg)
```


```{r}
ATUS<-read.dta("/Users/jiaoyu/Documents/Ph.D/projects/ATUS/data/atus_R.dta",convert.factors = F)

```


# Line plots
```{r message= F}
df<-ATUS%>%filter(age>59)%>%select("engage_h","engage_nh", "year", "race4", "weight", "month", "caseid", "female", "edu4" )%>%mutate(ym=format(lubridate::ym(paste0(year,month)), "%Y.%m"), eg=engage_h+engage_nh)
df$ym<-as.factor(df$ym)


sydata<-svydesign(id=~caseid, weights=~weight, data=df)

datline<-svyby(~engage_h + engage_nh+eg, ~ym,   sydata,svymean,  keep.var=TRUE)
names(datline)<-c("ym", "engage.1", "engage.2","engage.3", "se.1","se.2", "se.3")

line<-reshape(datline,
        direction = "long",
        idvar = "ym",       # i
        timevar = "group",  # j
        varying = c("engage.1", "engage.2", "engage.3","se.1","se.2","se.3"))
line$group<-factor(line$group, levels=c(1,2,3), labels=c("In home", "Out-of-home", "Total"))

line$upper<-line$engage+1.96*line$se
line$lower<-line$engage-1.96*line$se
line$time<-seq(1,nrow(line), 1)
```


```{r message= F}
lplot<-ggplot(data=line, aes(x = ym, y = engage, group = group)) +
  geom_rect(aes(xmin='2019.01',
                  xmax = '2019.12',
                  ymin = -Inf,
                  ymax = Inf),  fill = "grey85",  alpha = 0.03) +
    geom_rect(aes(xmin='2021.01',
                  xmax = '2021.12',
                  ymin = -Inf,
                  ymax = Inf),  fill = "grey85",  alpha = 0.03) +
  geom_line(aes(linetype = group), size=0.5) +
  geom_point(aes(shape=group), fill = "white", size = 1.5)+
 #geom_ribbon(aes(ymin=lower, ymax=upper), linetype=2, alpha=0.01)+
  
  geom_vline(xintercept = "2020.05",
               colour = "grey40",
               linetype = 2)+ # vertical line
 # geom_vline(xintercept = "2021.08",
              # colour = "grey40",
               #linetype = 2)+ # vertical line
  labs( x= "Month" , y= 'Time (min)',title= "", color="", type="")+
  theme_article()+
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust=1), legend.title = element_blank(),legend.text = element_text(size=12))+
     scale_linetype_manual(values =  c(  "longdash", "solid","dotted"))+
  coord_cartesian(ylim = c(0,100))
```

```{r warning=FALSE, message= F}
library(gganimate)


lplot+geom_point() +
  transition_reveal(time)
```

